### ISSUE TITLE
Feature request: weekly times

### ISSUE THREAD

**Issue by AurelienFocant** [arnaudderison/logtime19#1]
I thought it'd be great if we could see at a glance the weekly times, at least of the current week, particularly for checking phoenix advancement.

<img width="1470" alt="Screenshot 2024-12-18 at 20 21 41" src="https://github.com/user-attachments/assets/42f35767-8389-4d4b-a5ba-4a9798fd057d" />

**Comment by arnaudderison** [comment]
Feature now available :)
